services:
  currency-webui:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    ports:
        - "8000:5171"
    volumes:
        - ./src:/app/src
    profiles:
        - web
    working_dir: /app/src/WebUI
    command: dotnet run